# Generated by Django 2.0.2 on 2018-02-11 03:54

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('comment_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('commentxt', models.TextField(verbose_name='Comment Summary')),
                ('direction', models.CharField(choices=[('in', 'Incoming'), ('out', 'Outgoing')], max_length=3)),
                ('method', models.CharField(choices=[('phone', 'Phone Conversation'), ('email', 'Email Correspondence'), ('person', 'In-Person Conversation'), ('web', 'Sumitted on Web Form')], max_length=6)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=24, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=50, verbose_name='Last Name')),
                ('textnote', models.CharField(blank=True, max_length=120, verbose_name='Note')),
                ('org_title', models.CharField(blank=True, max_length=40, verbose_name='Title')),
                ('email', models.EmailField(blank=True, max_length=80, verbose_name='Email Address')),
                ('phone', models.CharField(blank=True, help_text='Phone: xxx-xxx-xxxx', max_length=12, verbose_name='Phone')),
                ('address', models.CharField(blank=True, max_length=60, verbose_name='Address 1')),
                ('address2', models.CharField(blank=True, max_length=24, verbose_name='Address 2')),
                ('city', models.CharField(blank=True, max_length=40, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=2, verbose_name='State')),
                ('zipcode', models.CharField(blank=True, max_length=10, verbose_name='ZIP')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=80, verbose_name='Organization Name')),
                ('org_address1', models.CharField(blank=True, max_length=60, verbose_name='Address1')),
                ('org_address2', models.CharField(blank=True, max_length=24, verbose_name='Address2')),
                ('org_city', models.CharField(blank=True, max_length=40, verbose_name='City')),
                ('org_state', models.CharField(blank=True, max_length=2, verbose_name='State')),
                ('org_zipcode', models.CharField(blank=True, max_length=10, verbose_name='ZIP')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=60)),
                ('initial_date', models.DateField(default=django.utils.timezone.now, verbose_name='Start Date')),
                ('coordinates', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contacts.Contact')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='contacts.Organization'),
        ),
        migrations.AddField(
            model_name='comment',
            name='contact',
            field=models.ForeignKey(help_text='Individual who contacted PI', on_delete=django.db.models.deletion.PROTECT, to='contacts.Contact'),
        ),
        migrations.AddField(
            model_name='comment',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contacts.Subject'),
        ),
    ]
