# Generated by Django 2.0.2 on 2018-03-02 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20180221_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='org_phone',
            field=models.CharField(blank=True, help_text='Phone: xxx-xxx-xxxx', max_length=12, verbose_name='Phone'),
        ),
    ]
