# Generated by Django 2.0.2 on 2018-02-19 19:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_comment_attachment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-comment_datetime']},
        ),
        migrations.AddField(
            model_name='subject',
            name='last_activity',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Activity'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='initial_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start Date'),
        ),
    ]
