# Generated by Django 2.0.2 on 2018-02-19 20:08

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20180219_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subject',
            name='coordinates',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326, verbose_name='Point Location'),
        ),
    ]
