# Generated by Django 2.0.2 on 2018-03-05 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_organization_org_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['-initial_date']},
        ),
    ]
