# Generated by Django 2.0.2 on 2018-02-19 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_auto_20180219_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='state',
            field=models.CharField(blank=True, default='UT', max_length=2, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='org_state',
            field=models.CharField(blank=True, default='UT', max_length=2, verbose_name='State'),
        ),
    ]
