# Generated by Django 2.0.2 on 2018-02-19 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_auto_20180219_1445'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='address',
            new_name='address1',
        ),
    ]
