# Generated by Django 2.0.2 on 2018-03-05 04:48

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PublicComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=500, verbose_name='Comment')),
                ('first_name', models.CharField(blank=True, max_length=24, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=50, verbose_name='Last Name')),
                ('email', models.EmailField(blank=True, max_length=80, verbose_name='Email Address')),
                ('phone', models.CharField(blank=True, help_text='Phone: xxx-xxx-xxxx', max_length=12, verbose_name='Phone')),
                ('address1', models.CharField(blank=True, max_length=60, verbose_name='Address 1')),
                ('address2', models.CharField(blank=True, max_length=24, verbose_name='Address 2')),
                ('city', models.CharField(blank=True, max_length=40, verbose_name='City')),
                ('state', models.CharField(blank=True, default='UT', max_length=2, verbose_name='State')),
                ('zipcode', models.CharField(blank=True, max_length=10, verbose_name='ZIP')),
                ('submitted', models.DateTimeField(auto_now_add=True, verbose_name='Submitted')),
                ('location', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326, verbose_name='Point Location')),
                ('bcookie', models.UUIDField(blank=True, editable=False)),
            ],
        ),
    ]
