# Generated by Django 2.0.2 on 2018-03-05 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pubinput', '0002_auto_20180305_1113'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publiccomment',
            options={'ordering': ['-submitted']},
        ),
    ]
